"""delete-orphan

Revision ID: 0002
Revises: 0001
Create Date: 2024-12-12 01:12:29.504803

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_logs_user_id_users", "logs", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_logs_user_id_users"),
        "logs",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("fk_purchases_user_id_users", "purchases", type_="foreignkey")
    op.drop_constraint(
        "fk_purchases_product_id_products",
        "purchases",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_purchases_user_id_users"),
        "purchases",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_purchases_product_id_products"),
        "purchases",
        "products",
        ["product_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_purchases_product_id_products"),
        "purchases",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_purchases_user_id_users"),
        "purchases",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_purchases_product_id_products",
        "purchases",
        "products",
        ["product_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_purchases_user_id_users",
        "purchases",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(op.f("fk_logs_user_id_users"), "logs", type_="foreignkey")
    op.create_foreign_key("fk_logs_user_id_users", "logs", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###
