"""reward

Revision ID: 0005
Revises: 0004
Create Date: 2024-12-12 02:50:06.140249

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_secrets_phrase"), "secrets", ["phrase"])
    op.drop_constraint(
        "fk_users_to_secrets_user_id_users",
        "users_to_secrets",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_users_to_secrets_secret_id_secrets",
        "users_to_secrets",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_users_to_secrets_user_id_users"),
        "users_to_secrets",
        "users",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_users_to_secrets_secret_id_secrets"),
        "users_to_secrets",
        "secrets",
        ["secret_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_users_to_secrets_secret_id_secrets"),
        "users_to_secrets",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_users_to_secrets_user_id_users"),
        "users_to_secrets",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_users_to_secrets_secret_id_secrets",
        "users_to_secrets",
        "secrets",
        ["secret_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_users_to_secrets_user_id_users",
        "users_to_secrets",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("uq_secrets_phrase"), "secrets", type_="unique")
    # ### end Alembic commands ###
