"""roles

Revision ID: 0007
Revises: 0006
Create Date: 2024-12-13 16:59:59.335228

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("role", sa.String(length=64), nullable=True))
    op.drop_column("users", "can_clear_purchases")
    op.drop_column("users", "is_admin")
    op.drop_column("users", "can_pay")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("can_pay", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("is_admin", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users",
        sa.Column(
            "can_clear_purchases",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("users", "role")
    # ### end Alembic commands ###
